name: hisaab
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.6
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  supabase_flutter: ^2.5.1
  table_calendar: ^3.1.2
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
