name: hisaab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  calendar_timeline: ^1.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  sizer: ^2.0.15
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
